### ISSUE TITLE
Return column names with n=1

### ISSUE THREAD

**Issue by Mitchellpkt** [Mitchellpkt/headtailx#2]
Since this library mimics the output of the `head` command applied to a csv file, requesting `-n 1` line should return the column names.

Suppose we have the test data
```
columnA,some_num,foo
4,9.3,pink
8,5,blue
6,,orchid
```

If  we run `headx test.txt -n 1` the **desired** result would be something similar to `columnA,some_num,foo`

The **actual** result is an error:
```
Traceback (most recent call last):
  File "/home/m/.local/bin/headx", line 8, in <module>
    sys.exit(main())
  File "/home/m/.local/lib/python3.10/site-packages/headtailx/headx.py", line 37, in main
    head_tail = HeadTail(
  File "/home/m/.local/lib/python3.10/site-packages/headtailx/headtailx_common.py", line 36, in __init__
    self._validate_arguments()
  File "/home/m/.local/lib/python3.10/site-packages/headtailx/headtailx_common.py", line 43, in _validate_arguments
    raise ValueError("Number of lines must be greater than 0.")
ValueError: Number of lines must be greater than 0.
```

**Comment by Mitchellpkt** [comment]
See PR #3

**Comment by Mitchellpkt** [comment]
#3 merged, solved
